#server:
#  port: 8080
#
#spring:
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/community
#    username: root
#    password: 1234
#
#  sql:
#    init:
#      mode: ALWAYS
#
#
#
#logging:
#  level:
#    org:
#      springframework.web: debug